(define (problem simpleira)
    (:domain agenteSeguranca)
    (:objects Sala1 Sala2 C1 J1 J2 P1)
    (:init (Em Sala2) (Sala Sala1) (Sala Sala2) (Corredor C1) (Acesa Sala1)
        (Apagada Sala2) (Janela Sala1 J1) (Janela Sala2 J2) (Fechada J1) 
        (Aberta J2) (Porta Sala1 Sala2 P1) (Fechada P1)
    )
    (:goal  ( and (Em Sala2) (Apagada Sala1) (Acesa Sala2) (Fechada J2) 
        (Aberta J1) ) )
)
